# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 121 # Min 88, Max 121
indent-width = 4


[lint]
select = ["ALL"]
ignore = [
  "COM812", # Trailing comma missing
  "D103", # Missing docstring in public function
  "D213", # no-blank-line-before-class (conflict with D212)
  "D203", # incorrect-blank-line-before-class (conflict with D211)
  "D100", # Missing docstring in public module
  "ANN001", # Missing type annotation for function argument
  "D104", # Missing docstring in public package
  "D101", # Missing docstring in public class
  "D106", # Missing docstring in public nested class
  "N815", # Variable `timeToLifeSec` in class scope should not be mixedCase *
  "ANN201", # Missing return type annotation for public function
  "ARG001", # Unused function argument
]

# 3. Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

# 4. Ignore `E402` (import violations) in all `__init__.py` files, and in selected subdirectories.
[lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]
# Ignore all directories named `tests`.
"tests/**" = ["PLR2004", "S101", "ANN201"]

[format]
quote-style = "double"
